;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2013 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3073-7154-46			    |
; |				  INRIA	NANCY				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	C76061CBB54AF38AD610DD62DA039597
; Input	CRC32 :	FAF9A600

; File Name   :	/media/sf_ccs2015/malardalen/statemate.exe
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 0000193C (   6460.)
; Section size in file		: 00001A00 (   6656.)
; Offset to raw	data for section: 00000400
; Flags	60300020: Text Executable Readable
; Alignment	: 4 bytes

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text		segment	dword public 'CODE' use32
		assume cs:_text
		;org 401000h
		assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

		public start
start		proc near
		push	ebp
		mov	ebp, esp
		sub	esp, 8
		call	sub_402912
		leave
		retn
start		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_40100D	proc near		; CODE XREF: sub_402912+8p

var_10		= qword	ptr -10h
var_8		= qword	ptr -8

		push	ebp
		mov	ebp, esp
		sub	esp, 10h
		movzx	eax, ds:byte_406004
		test	al, al
		jz	short loc_401028
		mov	eax, ds:dword_4060C0
		mov	ds:dword_406070, eax

loc_401028:				; CODE XREF: sub_40100D+Fj
		movzx	eax, ds:byte_406004
		test	al, al
		jnz	short loc_40103E
		movzx	eax, ds:byte_406006
		test	al, al
		jz	short loc_401048

loc_40103E:				; CODE XREF: sub_40100D+24j
		mov	eax, ds:dword_4060C0
		mov	ds:dword_4060FC, eax

loc_401048:				; CODE XREF: sub_40100D+2Fj
		mov	eax, ds:dword_4060B8
		test	eax, eax
		jz	short loc_401092
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_4060B8
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403000
		fxch	st(1)
		fucomip	st, st(1)
		fstp	st
		jb	short loc_401092
		mov	ds:byte_406116,	0
		mov	ds:dword_4060B8, 0

loc_401092:				; CODE XREF: sub_40100D+42j
					; sub_40100D+72j
		mov	eax, ds:dword_406060
		test	eax, eax
		jz	short loc_4010DC
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_406060
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403000
		fxch	st(1)
		fucomip	st, st(1)
		fstp	st
		jb	short loc_4010DC
		mov	ds:byte_4060ED,	0
		mov	ds:dword_406060, 0

loc_4010DC:				; CODE XREF: sub_40100D+8Cj
					; sub_40100D+BCj
		mov	eax, ds:dword_4060B0
		test	eax, eax
		jz	short loc_401126
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_4060B0
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403000
		fxch	st(1)
		fucomip	st, st(1)
		fstp	st
		jb	short loc_401126
		mov	ds:byte_4060ED,	0
		mov	ds:dword_4060B0, 0

loc_401126:				; CODE XREF: sub_40100D+D6j
					; sub_40100D+106j
		mov	eax, ds:dword_406040
		test	eax, eax
		jz	short loc_401169
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_406040
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403000
		fxch	st(1)
		fucomip	st, st(1)
		fstp	st
		jb	short loc_401169
		mov	ds:dword_406040, 0

loc_401169:				; CODE XREF: sub_40100D+120j
					; sub_40100D+150j
		mov	eax, ds:dword_4060A0
		test	eax, eax
		jz	short loc_4011AC
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_4060A0
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403000
		fxch	st(1)
		fucomip	st, st(1)
		fstp	st
		jb	short loc_4011AC
		mov	ds:dword_4060A0, 0

loc_4011AC:				; CODE XREF: sub_40100D+163j
					; sub_40100D+193j
		movzx	eax, ds:byte_406000
		test	al, al
		jnz	short loc_4011C6
		mov	edx, ds:dword_40604C
		mov	eax, ds:dword_40609C
		cmp	edx, eax
		jz	short locret_4011D0

loc_4011C6:				; CODE XREF: sub_40100D+1A8j
		mov	eax, ds:dword_4060C0
		mov	ds:dword_40610C, eax

locret_4011D0:				; CODE XREF: sub_40100D+1B7j
		leave
		retn
sub_40100D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4011D2	proc near		; CODE XREF: sub_402912+3p
		push	ebp
		mov	ebp, esp
		mov	ds:dword_40610C, 0
		mov	ds:dword_4060FC, 0
		mov	ds:dword_406070, 0
		mov	ds:byte_4060F8,	0
		mov	ds:byte_4060E9,	0
		mov	ds:byte_406096,	0
		mov	ds:byte_4060F6,	0
		mov	ds:byte_4060D8,	0
		mov	ds:byte_4060EA,	0
		mov	ds:byte_406078,	0
		mov	ds:byte_406045,	0
		mov	ds:byte_406044,	0
		mov	ds:byte_4060C7,	0
		mov	ds:byte_406081,	0
		mov	ds:byte_406111,	0
		mov	ds:byte_4060FA,	0
		mov	ds:byte_406114,	0
		mov	ds:byte_406102,	0
		mov	ds:byte_4060A9,	0
		pop	ebp
		retn
sub_4011D2	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401265	proc near		; CODE XREF: sub_40219F+2F4p
		push	ebp
		mov	ebp, esp
		movzx	eax, ds:byte_40600A
		test	al, al
		jz	loc_401637
		movzx	eax, ds:byte_4060F6
		movsx	eax, al
		cmp	eax, 2
		jz	loc_4013B3
		cmp	eax, 3
		jz	loc_4014CA
		cmp	eax, 1
		jnz	loc_401628
		movzx	eax, ds:byte_406098
		test	al, al
		jnz	short loc_4012DA
		movzx	eax, ds:byte_406047
		test	al, al
		jnz	short loc_4012DA
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	0
		mov	ds:byte_4060C6,	0
		mov	ds:byte_4060F6,	3
		mov	ds:byte_4060E9,	0
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_4012DA:				; CODE XREF: sub_401265+40j
					; sub_401265+4Bj
		movzx	eax, ds:byte_4060E9
		movsx	eax, al
		cmp	eax, 1
		jnz	loc_4013A6
		movzx	eax, ds:byte_406098
		test	al, al
		jz	short loc_40131D
		movzx	eax, ds:byte_4060C8
		test	al, al
		jnz	short loc_40131D
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	1
		mov	ds:byte_4060E9,	1
		jmp	loc_4013AE
; ---------------------------------------------------------------------------

loc_40131D:				; CODE XREF: sub_401265+91j
					; sub_401265+9Cj
		movzx	eax, ds:byte_406047
		test	al, al
		jz	short loc_40134A
		movzx	eax, ds:byte_406097
		test	al, al
		jnz	short loc_40134A
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	1
		mov	ds:byte_4060E9,	1
		jmp	short loc_4013AE
; ---------------------------------------------------------------------------

loc_40134A:				; CODE XREF: sub_401265+C1j
					; sub_401265+CCj
		movzx	eax, ds:byte_406098
		test	al, al
		jnz	short loc_401377
		movzx	eax, ds:byte_4060C8
		test	al, al
		jz	short loc_401377
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	0
		mov	ds:byte_4060E9,	1
		jmp	short loc_4013AE
; ---------------------------------------------------------------------------

loc_401377:				; CODE XREF: sub_401265+EEj
					; sub_401265+F9j
		movzx	eax, ds:byte_406047
		test	al, al
		jnz	short loc_4013A4
		movzx	eax, ds:byte_406097
		test	al, al
		jz	short loc_4013A4
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	0
		mov	ds:byte_4060E9,	1
		jmp	short loc_4013AE
; ---------------------------------------------------------------------------

loc_4013A4:				; CODE XREF: sub_401265+11Bj
					; sub_401265+126j
		jmp	short loc_4013AE
; ---------------------------------------------------------------------------

loc_4013A6:				; CODE XREF: sub_401265+82j
		mov	ds:byte_4060A4,	0
		nop

loc_4013AE:				; CODE XREF: sub_401265+B3j
					; sub_401265+E3j ...
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_4013B3:				; CODE XREF: sub_401265+1Fj
		movzx	eax, ds:byte_4060A5
		test	al, al
		jnz	short loc_4013F1
		movzx	eax, ds:byte_4060C5
		test	al, al
		jnz	short loc_4013F1
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	0
		mov	ds:byte_4060C6,	0
		mov	ds:byte_4060F6,	3
		mov	ds:byte_406096,	0
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_4013F1:				; CODE XREF: sub_401265+157j
					; sub_401265+162j
		movzx	eax, ds:byte_406096
		movsx	eax, al
		cmp	eax, 1
		jnz	loc_4014BD
		movzx	eax, ds:byte_4060A5
		test	al, al
		jz	short loc_401434
		movzx	eax, ds:byte_4060F5
		test	al, al
		jnz	short loc_401434
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	1
		mov	ds:byte_406096,	1
		jmp	loc_4014C5
; ---------------------------------------------------------------------------

loc_401434:				; CODE XREF: sub_401265+1A8j
					; sub_401265+1B3j
		movzx	eax, ds:byte_4060C5
		test	al, al
		jz	short loc_401461
		movzx	eax, ds:byte_406099
		test	al, al
		jnz	short loc_401461
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	1
		mov	ds:byte_406096,	1
		jmp	short loc_4014C5
; ---------------------------------------------------------------------------

loc_401461:				; CODE XREF: sub_401265+1D8j
					; sub_401265+1E3j
		movzx	eax, ds:byte_4060A5
		test	al, al
		jnz	short loc_40148E
		movzx	eax, ds:byte_4060F5
		test	al, al
		jz	short loc_40148E
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	0
		mov	ds:byte_406096,	1
		jmp	short loc_4014C5
; ---------------------------------------------------------------------------

loc_40148E:				; CODE XREF: sub_401265+205j
					; sub_401265+210j
		movzx	eax, ds:byte_4060C5
		test	al, al
		jnz	short loc_4014BB
		movzx	eax, ds:byte_406099
		test	al, al
		jz	short loc_4014BB
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	0
		mov	ds:byte_406096,	1
		jmp	short loc_4014C5
; ---------------------------------------------------------------------------

loc_4014BB:				; CODE XREF: sub_401265+232j
					; sub_401265+23Dj
		jmp	short loc_4014C5
; ---------------------------------------------------------------------------

loc_4014BD:				; CODE XREF: sub_401265+199j
		mov	ds:byte_4060A4,	0
		nop

loc_4014C5:				; CODE XREF: sub_401265+1CAj
					; sub_401265+1FAj ...
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_4014CA:				; CODE XREF: sub_401265+28j
		movzx	eax, ds:byte_4060F7
		test	al, al
		jnz	short loc_40150C
		movzx	eax, ds:byte_4060C5
		test	al, al
		jz	short loc_40150C
		movzx	eax, ds:byte_4060A5
		test	al, al
		jz	short loc_40150C
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	1
		mov	ds:byte_4060C6,	1
		mov	ds:byte_4060F6,	2
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_40150C:				; CODE XREF: sub_401265+26Ej
					; sub_401265+279j ...
		movzx	eax, ds:byte_4060F7
		test	al, al
		jnz	short loc_401547
		movzx	eax, ds:byte_4060C5
		test	al, al
		jz	short loc_401547
		movzx	eax, ds:byte_4060A5
		test	al, al
		jnz	short loc_401547
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	1
		mov	ds:byte_4060F6,	2
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_401547:				; CODE XREF: sub_401265+2B0j
					; sub_401265+2BBj ...
		movzx	eax, ds:byte_4060F7
		test	al, al
		jnz	short loc_401582
		movzx	eax, ds:byte_4060C5
		test	al, al
		jnz	short loc_401582
		movzx	eax, ds:byte_4060A5
		test	al, al
		jz	short loc_401582
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	1
		mov	ds:byte_4060F6,	2
		jmp	loc_401637
; ---------------------------------------------------------------------------

loc_401582:				; CODE XREF: sub_401265+2EBj
					; sub_401265+2F6j ...
		movzx	eax, ds:byte_406047
		test	al, al
		jnz	short loc_4015BA
		movzx	eax, ds:byte_406098
		test	al, al
		jz	short loc_4015BA
		movzx	eax, ds:byte_4060F7
		test	al, al
		jnz	short loc_4015BA
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	1
		mov	ds:byte_4060F6,	1
		jmp	short loc_401637
; ---------------------------------------------------------------------------

loc_4015BA:				; CODE XREF: sub_401265+326j
					; sub_401265+331j ...
		movzx	eax, ds:byte_406047
		test	al, al
		jz	short loc_4015EE
		movzx	eax, ds:byte_406098
		test	al, al
		jz	short loc_4015EE
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C6,	1
		mov	ds:byte_4060FB,	1
		mov	ds:byte_4060F6,	1
		jmp	short loc_401637
; ---------------------------------------------------------------------------

loc_4015EE:				; CODE XREF: sub_401265+35Ej
					; sub_401265+369j
		movzx	eax, ds:byte_406047
		test	al, al
		jz	short loc_401626
		movzx	eax, ds:byte_406098
		test	al, al
		jnz	short loc_401626
		movzx	eax, ds:byte_4060F7
		test	al, al
		jnz	short loc_401626
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060FB,	1
		mov	ds:byte_4060F6,	1
		jmp	short loc_401637
; ---------------------------------------------------------------------------

loc_401626:				; CODE XREF: sub_401265+392j
					; sub_401265+39Dj ...
		jmp	short loc_401637
; ---------------------------------------------------------------------------

loc_401628:				; CODE XREF: sub_401265+31j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060F6,	3
		nop

loc_401637:				; CODE XREF: sub_401265+Cj
					; sub_401265+70j ...
		pop	ebp
		retn
sub_401265	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401639	proc near		; CODE XREF: sub_40219F+3B5p
		push	ebp
		mov	ebp, esp
		movzx	eax, ds:byte_40600D
		test	al, al
		jnz	short loc_40166B
		movzx	eax, ds:byte_40600F
		test	al, al
		jz	short loc_40166B
		movzx	eax, ds:byte_40600E
		test	al, al
		jnz	short loc_40166B
		mov	ds:byte_406004,	0
		mov	ds:byte_406006,	0

loc_40166B:				; CODE XREF: sub_401639+Cj
					; sub_401639+17j ...
		movzx	eax, ds:byte_40600D
		test	al, al
		jz	loc_401EB4
		movzx	eax, ds:byte_40600A
		test	al, al
		jnz	short loc_40168C
		mov	ds:byte_4060F6,	3

loc_40168C:				; CODE XREF: sub_401639+4Aj
		mov	ds:byte_40600B,	0
		movzx	eax, ds:byte_406013
		test	al, al
		jnz	short loc_4016AC
		mov	ds:byte_406000,	0
		mov	ds:byte_4060A9,	1

loc_4016AC:				; CODE XREF: sub_401639+63j
		mov	ds:byte_406014,	0
		mov	ds:byte_40600B,	1
		mov	ds:byte_406014,	1
		movzx	eax, ds:byte_4060D8
		movsx	eax, al
		cmp	eax, 2
		jz	short loc_401715
		cmp	eax, 3
		jz	loc_401820
		cmp	eax, 1
		jnz	loc_401D53
		mov	eax, ds:dword_406058
		cmp	eax, 3Bh
		jnz	short loc_401710
		mov	eax, ds:dword_4060D4
		cmp	eax, 3Bh
		jz	short loc_401710
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060D8,	3
		mov	ds:byte_406045,	3
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_401710:				; CODE XREF: sub_401639+B1j
					; sub_401639+BBj
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_401715:				; CODE XREF: sub_401639+95j
		movzx	eax, ds:byte_406094
		test	al, al
		jz	short loc_401761
		movzx	eax, ds:byte_4060AB
		test	al, al
		jnz	short loc_401761
		movzx	eax, ds:byte_4060B5
		test	al, al
		jz	short loc_401761
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	eax, ds:dword_4060C0
		mov	ds:dword_4060B0, eax
		mov	ds:byte_4060D8,	3
		mov	ds:byte_406045,	3
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_401761:				; CODE XREF: sub_401639+E5j
					; sub_401639+F0j ...
		movzx	eax, ds:byte_4060F8
		movsx	eax, al
		cmp	eax, 2
		jz	short loc_4017A2
		cmp	eax, 3
		jz	short loc_4017C6
		cmp	eax, 1
		jnz	loc_40180C
		movzx	eax, ds:byte_4060F4
		test	al, al
		jnz	short loc_4017A0
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_4060F8,	3
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_4017A0:				; CODE XREF: sub_401639+14Ej
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_4017A2:				; CODE XREF: sub_401639+135j
		movzx	eax, ds:byte_406083
		test	al, al
		jnz	short loc_4017C4
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	0
		mov	ds:byte_4060F8,	3
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_4017C4:				; CODE XREF: sub_401639+172j
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_4017C6:				; CODE XREF: sub_401639+13Aj
		movzx	eax, ds:byte_406083
		test	al, al
		jz	short loc_4017E8
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	1
		mov	ds:byte_4060F8,	2
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_4017E8:				; CODE XREF: sub_401639+196j
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_40180A
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	1
		mov	ds:byte_4060F8,	1
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_40180A:				; CODE XREF: sub_401639+1B8j
		jmp	short loc_40181B
; ---------------------------------------------------------------------------

loc_40180C:				; CODE XREF: sub_401639+13Fj
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060F8,	3
		nop

loc_40181B:				; CODE XREF: sub_401639+165j
					; sub_401639:loc_4017A0j ...
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_401820:				; CODE XREF: sub_401639+9Aj
		mov	eax, ds:dword_406058
		cmp	eax, 3Ch
		jle	short loc_40186B
		mov	eax, ds:dword_4060D4
		cmp	eax, 3Ch
		jg	short loc_40186B
		movzx	eax, ds:byte_406050
		test	al, al
		jnz	short loc_40186B
		movzx	eax, ds:byte_40606E
		test	al, al
		jnz	short loc_40186B
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_406116,	0
		mov	ds:byte_4060D8,	1
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_40186B:				; CODE XREF: sub_401639+1EFj
					; sub_401639+1F9j ...
		movzx	eax, ds:byte_406094
		test	al, al
		jz	short loc_4018B7
		movzx	eax, ds:byte_4060AB
		test	al, al
		jnz	short loc_4018B7
		movzx	eax, ds:byte_406108
		test	al, al
		jz	short loc_4018B7
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	0
		mov	eax, ds:dword_4060C0
		mov	ds:dword_4060B8, eax
		mov	ds:byte_4060D8,	2
		mov	ds:byte_4060F8,	3
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_4018B7:				; CODE XREF: sub_401639+23Bj
					; sub_401639+246j ...
		movzx	eax, ds:byte_406094
		test	al, al
		jz	short loc_401903
		movzx	eax, ds:byte_4060AB
		test	al, al
		jnz	short loc_401903
		movzx	eax, ds:byte_4060B5
		test	al, al
		jz	short loc_401903
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	eax, ds:dword_4060C0
		mov	ds:dword_406060, eax
		mov	ds:byte_4060D8,	2
		mov	ds:byte_4060F8,	3
		jmp	loc_401D62
; ---------------------------------------------------------------------------

loc_401903:				; CODE XREF: sub_401639+287j
					; sub_401639+292j ...
		movzx	eax, ds:byte_406045
		movsx	eax, al
		cmp	eax, 2
		jz	loc_401A23
		cmp	eax, 3
		jz	loc_401CB5
		cmp	eax, 1
		jnz	loc_401D42
		mov	eax, ds:dword_4060F0
		cmp	eax, 194h
		jle	short loc_40194E
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	0
		mov	ds:byte_406045,	3
		jmp	loc_401D51
; ---------------------------------------------------------------------------

loc_40194E:				; CODE XREF: sub_401639+2F9j
		movzx	eax, ds:byte_406081
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401967
		cmp	eax, 2
		jz	short loc_4019B3
		jmp	loc_401A0F
; ---------------------------------------------------------------------------

loc_401967:				; CODE XREF: sub_401639+322j
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_40197D
		movzx	eax, ds:byte_40606D
		test	al, al
		jz	short loc_401993

loc_40197D:				; CODE XREF: sub_401639+337j
		movzx	eax, ds:byte_406083
		test	al, al
		jz	short loc_4019B1
		movzx	eax, ds:byte_406084
		test	al, al
		jnz	short loc_4019B1

loc_401993:				; CODE XREF: sub_401639+342j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	0
		mov	ds:byte_406045,	3
		mov	ds:byte_406081,	0
		jmp	short loc_401A1E
; ---------------------------------------------------------------------------

loc_4019B1:				; CODE XREF: sub_401639+34Dj
					; sub_401639+358j
		jmp	short loc_401A1E
; ---------------------------------------------------------------------------

loc_4019B3:				; CODE XREF: sub_401639+327j
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_4019D9
		movzx	eax, ds:byte_40606D
		test	al, al
		jnz	short loc_4019D9
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406081,	1
		jmp	short loc_401A1E
; ---------------------------------------------------------------------------

loc_4019D9:				; CODE XREF: sub_401639+383j
					; sub_401639+38Ej
		movzx	eax, ds:byte_406083
		test	al, al
		jnz	short loc_401A0D
		movzx	eax, ds:byte_406084
		test	al, al
		jz	short loc_401A0D
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	0
		mov	ds:byte_406045,	3
		mov	ds:byte_406081,	0
		jmp	short loc_401A1E
; ---------------------------------------------------------------------------

loc_401A0D:				; CODE XREF: sub_401639+3A9j
					; sub_401639+3B4j
		jmp	short loc_401A1E
; ---------------------------------------------------------------------------

loc_401A0F:				; CODE XREF: sub_401639+329j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406081,	2
		nop

loc_401A1E:				; CODE XREF: sub_401639+376j
					; sub_401639:loc_4019B1j ...
		jmp	loc_401D51
; ---------------------------------------------------------------------------

loc_401A23:				; CODE XREF: sub_401639+2D7j
		mov	eax, ds:dword_4060F0
		test	eax, eax
		jg	short loc_401A46
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_406045,	3
		jmp	loc_401D51
; ---------------------------------------------------------------------------

loc_401A46:				; CODE XREF: sub_401639+3F1j
		movzx	eax, ds:byte_406111
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401A63
		cmp	eax, 2
		jz	loc_401B67
		jmp	loc_401C8C
; ---------------------------------------------------------------------------

loc_401A63:				; CODE XREF: sub_401639+41Aj
		movzx	eax, ds:byte_406083
		test	al, al
		jz	short loc_401A79
		movzx	eax, ds:byte_406084
		test	al, al
		jz	short loc_401A8F

loc_401A79:				; CODE XREF: sub_401639+433j
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_401AA9
		movzx	eax, ds:byte_40606D
		test	al, al
		jnz	short loc_401AA9

loc_401A8F:				; CODE XREF: sub_401639+43Ej
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_406045,	3
		jmp	loc_401CB0
; ---------------------------------------------------------------------------

loc_401AA9:				; CODE XREF: sub_401639+449j
					; sub_401639+454j
		movzx	eax, ds:byte_406044
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401AC2
		cmp	eax, 2
		jz	short loc_401B02
		jmp	loc_401B4C
; ---------------------------------------------------------------------------

loc_401AC2:				; CODE XREF: sub_401639+47Dj
		mov	ds:byte_406017,	0
		movzx	eax, ds:byte_406016
		test	al, al
		jz	short loc_401B00
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	1
		mov	ds:byte_40606C,	0
		mov	ds:byte_406044,	2
		mov	ds:byte_406116,	0
		mov	ds:byte_406011,	1
		jmp	short loc_401B62
; ---------------------------------------------------------------------------

loc_401B00:				; CODE XREF: sub_401639+499j
		jmp	short loc_401B62
; ---------------------------------------------------------------------------

loc_401B02:				; CODE XREF: sub_401639+482j
		movzx	eax, ds:byte_406018
		test	al, al
		jz	short loc_401B4A
		mov	ds:byte_4060A4,	0
		mov	ds:byte_40606C,	1
		mov	ds:byte_406017,	1
		mov	ds:byte_406044,	1
		mov	ds:byte_406011,	0
		mov	ds:byte_4060ED,	0
		mov	eax, ds:dword_4060C0
		mov	ds:dword_406040, eax
		mov	ds:byte_406116,	1
		jmp	short loc_401B62
; ---------------------------------------------------------------------------

loc_401B4A:				; CODE XREF: sub_401639+4D2j
		jmp	short loc_401B62
; ---------------------------------------------------------------------------

loc_401B4C:				; CODE XREF: sub_401639+484j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406044,	2
		mov	ds:byte_406011,	1
		nop

loc_401B62:				; CODE XREF: sub_401639+4C5j
					; sub_401639:loc_401B00j ...
		jmp	loc_401CB0
; ---------------------------------------------------------------------------

loc_401B67:				; CODE XREF: sub_401639+41Fj
		movzx	eax, ds:byte_4060F4
		test	al, al
		jnz	short loc_401B97
		movzx	eax, ds:byte_40606D
		test	al, al
		jz	short loc_401B97
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_406045,	3
		jmp	loc_401CB0
; ---------------------------------------------------------------------------

loc_401B97:				; CODE XREF: sub_401639+537j
					; sub_401639+542j
		movzx	eax, ds:byte_4060C7
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401BB0
		cmp	eax, 2
		jz	short loc_401BF6
		jmp	loc_401C6D
; ---------------------------------------------------------------------------

loc_401BB0:				; CODE XREF: sub_401639+56Bj
		mov	ds:byte_406017,	0
		movzx	eax, ds:byte_406016
		test	al, al
		jz	short loc_401BF1
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406095,	0
		mov	ds:byte_4060C7,	2
		mov	ds:byte_406116,	0
		mov	ds:byte_406011,	1
		mov	ds:byte_4060ED,	1
		jmp	loc_401C8A
; ---------------------------------------------------------------------------

loc_401BF1:				; CODE XREF: sub_401639+587j
		jmp	loc_401C8A
; ---------------------------------------------------------------------------

loc_401BF6:				; CODE XREF: sub_401639+570j
		movzx	eax, ds:byte_406018
		test	al, al
		jz	short loc_401C3E
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060ED,	0
		mov	ds:byte_406095,	1
		mov	ds:byte_406017,	1
		mov	ds:byte_4060C7,	1
		mov	ds:byte_406011,	0
		mov	eax, ds:dword_4060C0
		mov	ds:dword_4060A0, eax
		mov	ds:byte_406116,	1
		jmp	short loc_401C8A
; ---------------------------------------------------------------------------

loc_401C3E:				; CODE XREF: sub_401639+5C6j
		movzx	eax, ds:byte_406083
		test	al, al
		jz	short loc_401C6B
		movzx	eax, ds:byte_406084
		test	al, al
		jnz	short loc_401C6B
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406111,	1
		mov	ds:byte_4060C7,	0
		jmp	short loc_401C8A
; ---------------------------------------------------------------------------

loc_401C6B:				; CODE XREF: sub_401639+60Ej
					; sub_401639+619j
		jmp	short loc_401C8A
; ---------------------------------------------------------------------------

loc_401C6D:				; CODE XREF: sub_401639+572j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060C7,	2
		mov	ds:byte_406011,	1
		mov	ds:byte_4060ED,	1
		nop

loc_401C8A:				; CODE XREF: sub_401639+5B3j
					; sub_401639:loc_401BF1j ...
		jmp	short loc_401CB0
; ---------------------------------------------------------------------------

loc_401C8C:				; CODE XREF: sub_401639+425j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406111,	2
		mov	ds:byte_4060C7,	2
		mov	ds:byte_406011,	1
		mov	ds:byte_4060ED,	1
		nop

loc_401CB0:				; CODE XREF: sub_401639+46Bj
					; sub_401639:loc_401B62j ...
		jmp	loc_401D51
; ---------------------------------------------------------------------------

loc_401CB5:				; CODE XREF: sub_401639+2E0j
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_401D00
		movzx	eax, ds:byte_40606D
		test	al, al
		jnz	short loc_401D00
		mov	eax, ds:dword_4060F0
		test	eax, eax
		jle	short loc_401D00
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406045,	2
		mov	ds:byte_406111,	2
		mov	ds:byte_4060C7,	2
		mov	ds:byte_406011,	1
		mov	ds:byte_4060ED,	1
		jmp	short loc_401D51
; ---------------------------------------------------------------------------

loc_401D00:				; CODE XREF: sub_401639+685j
					; sub_401639+690j ...
		movzx	eax, ds:byte_406083
		test	al, al
		jz	short loc_401D40
		movzx	eax, ds:byte_406084
		test	al, al
		jnz	short loc_401D40
		mov	eax, ds:dword_4060F0
		cmp	eax, 194h
		jg	short loc_401D40
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406116,	1
		mov	ds:byte_406045,	1
		mov	ds:byte_406081,	2
		jmp	short loc_401D51
; ---------------------------------------------------------------------------

loc_401D40:				; CODE XREF: sub_401639+6D0j
					; sub_401639+6DBj ...
		jmp	short loc_401D51
; ---------------------------------------------------------------------------

loc_401D42:				; CODE XREF: sub_401639+2E9j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406045,	3
		nop

loc_401D51:				; CODE XREF: sub_401639+310j
					; sub_401639:loc_401A1Ej ...
		jmp	short loc_401D62
; ---------------------------------------------------------------------------

loc_401D53:				; CODE XREF: sub_401639+A3j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060D8,	2
		nop

loc_401D62:				; CODE XREF: sub_401639+D2j
					; sub_401639:loc_401710j ...
		movzx	eax, ds:byte_4060EA
		movsx	eax, al
		cmp	eax, 1
		jnz	loc_401E75
		mov	ds:byte_406005,	0
		movzx	eax, ds:byte_4060AE
		cmp	al, 1
		jnz	short loc_401DE8
		mov	eax, ds:dword_4060FC
		test	eax, eax
		jz	short loc_401DE8
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_4060FC
		sub	edx, eax
		mov	eax, edx
		cmp	eax, 1
		jnz	short loc_401DE8
		movzx	eax, ds:byte_4060B5
		test	al, al
		jnz	short loc_401DBA
		movzx	eax, ds:byte_406108
		test	al, al
		jz	short loc_401DE8

loc_401DBA:				; CODE XREF: sub_401639+774j
		mov	ds:byte_4060A4,	0
		mov	eax, ds:dword_406058
		add	eax, 1
		mov	ds:dword_406058, eax
		mov	ds:byte_4060EA,	1
		mov	ds:byte_406005,	1
		mov	ds:byte_406078,	1
		jmp	loc_401E9C
; ---------------------------------------------------------------------------

loc_401DE8:				; CODE XREF: sub_401639+74Cj
					; sub_401639+755j ...
		movzx	eax, ds:byte_406078
		movsx	eax, al
		cmp	eax, 1
		jnz	short loc_401E5D
		movzx	eax, ds:byte_4060AE
		cmp	al, 1
		jnz	short loc_401E5B
		mov	eax, ds:dword_406070
		test	eax, eax
		jz	short loc_401E5B
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_406070
		sub	edx, eax
		mov	eax, edx
		cmp	eax, 3
		jnz	short loc_401E5B
		movzx	eax, ds:byte_4060B5
		test	al, al
		jnz	short loc_401E5B
		movzx	eax, ds:byte_406108
		test	al, al
		jnz	short loc_401E5B
		mov	eax, ds:dword_406058
		test	eax, eax
		jle	short loc_401E5B
		mov	ds:byte_4060A4,	0
		mov	eax, ds:dword_406058
		sub	eax, 1
		mov	ds:dword_406058, eax
		mov	ds:byte_406078,	1
		jmp	short loc_401E73
; ---------------------------------------------------------------------------

loc_401E5B:				; CODE XREF: sub_401639+7C7j
					; sub_401639+7D0j ...
		jmp	short loc_401E73
; ---------------------------------------------------------------------------

loc_401E5D:				; CODE XREF: sub_401639+7BCj
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406005,	1
		mov	ds:byte_406078,	1
		nop

loc_401E73:				; CODE XREF: sub_401639+820j
					; sub_401639:loc_401E5Bj
		jmp	short loc_401E9C
; ---------------------------------------------------------------------------

loc_401E75:				; CODE XREF: sub_401639+736j
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406058, 0
		mov	ds:byte_4060EA,	1
		mov	ds:byte_406005,	1
		mov	ds:byte_406078,	1
		nop

loc_401E9C:				; CODE XREF: sub_401639+7AAj
					; sub_401639:loc_401E73j
		movzx	eax, ds:byte_406004
		mov	ds:byte_406005,	al
		movzx	eax, ds:byte_406006
		mov	ds:byte_406007,	al

loc_401EB4:				; CODE XREF: sub_401639+3Bj
		pop	ebp
		retn
sub_401639	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401EB6	proc near		; CODE XREF: sub_40219F+476p
		push	ebp
		mov	ebp, esp
		movzx	eax, ds:byte_406010
		test	al, al
		jz	loc_401F61
		movzx	eax, ds:byte_406114
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401EDE
		cmp	eax, 2
		jz	short loc_401F23
		jmp	short loc_401F52
; ---------------------------------------------------------------------------

loc_401EDE:				; CODE XREF: sub_401EB6+1Fj
		movzx	eax, ds:byte_4060AF
		test	al, al
		jz	short loc_401F21
		movzx	eax, ds:byte_4060E8
		test	al, al
		jnz	short loc_401F21
		movzx	eax, ds:byte_4060F4
		test	al, al
		jz	short loc_401F0A
		movzx	eax, ds:byte_406083
		test	al, al
		jnz	short loc_401F21

loc_401F0A:				; CODE XREF: sub_401EB6+47j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406018,	1
		mov	ds:byte_406114,	2
		jmp	short loc_401F61
; ---------------------------------------------------------------------------

loc_401F21:				; CODE XREF: sub_401EB6+31j
					; sub_401EB6+3Cj ...
		jmp	short loc_401F61
; ---------------------------------------------------------------------------

loc_401F23:				; CODE XREF: sub_401EB6+24j
		mov	ds:byte_406018,	0
		movzx	eax, ds:byte_4060AF
		test	al, al
		jnz	short loc_401F50
		movzx	eax, ds:byte_4060E8
		test	al, al
		jz	short loc_401F50
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406114,	1
		jmp	short loc_401F61
; ---------------------------------------------------------------------------

loc_401F50:				; CODE XREF: sub_401EB6+7Dj
					; sub_401EB6+88j
		jmp	short loc_401F61
; ---------------------------------------------------------------------------

loc_401F52:				; CODE XREF: sub_401EB6+26j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406114,	1
		nop

loc_401F61:				; CODE XREF: sub_401EB6+Cj
					; sub_401EB6+69j ...
		pop	ebp
		retn
sub_401EB6	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401F63	proc near		; CODE XREF: sub_40219F+537p

var_10		= qword	ptr -10h
var_8		= qword	ptr -8

		push	ebp
		mov	ebp, esp
		sub	esp, 10h
		movzx	eax, ds:byte_406013
		test	al, al
		jnz	short loc_401F91
		movzx	eax, ds:byte_406015
		test	al, al
		jz	short loc_401F91
		movzx	eax, ds:byte_406014
		test	al, al
		jnz	short loc_401F91
		mov	ds:byte_406000,	0

loc_401F91:				; CODE XREF: sub_401F63+Fj
					; sub_401F63+1Aj ...
		movzx	eax, ds:byte_406013
		test	al, al
		jz	locret_40219D
		movzx	eax, ds:byte_4060A9
		movsx	eax, al
		cmp	eax, 1
		jz	short loc_401FB9
		cmp	eax, 2
		jz	short loc_402012
		jmp	loc_40218E
; ---------------------------------------------------------------------------

loc_401FB9:				; CODE XREF: sub_401F63+4Aj
		mov	edx, ds:dword_406054
		mov	eax, ds:dword_4060DC
		cmp	edx, eax
		jz	short loc_40200D
		mov	eax, ds:dword_406054
		test	eax, eax
		jle	short loc_40200D
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060A8,	0
		mov	ds:byte_4060A9,	2
		mov	ds:dword_40604C, 0
		mov	ds:dword_40607C, 2
		mov	ds:byte_406102,	3
		mov	ds:byte_406000,	1
		jmp	locret_40219D
; ---------------------------------------------------------------------------

loc_40200D:				; CODE XREF: sub_401F63+63j
					; sub_401F63+6Cj
		jmp	locret_40219D
; ---------------------------------------------------------------------------

loc_402012:				; CODE XREF: sub_401F63+4Fj
		movzx	eax, ds:byte_406108
		test	al, al
		jnz	short loc_402028
		movzx	eax, ds:byte_4060A6
		test	al, al
		jnz	short loc_40203E

loc_402028:				; CODE XREF: sub_401F63+B8j
		movzx	eax, ds:byte_4060B5
		test	al, al
		jnz	short loc_402058
		movzx	eax, ds:byte_40605C
		test	al, al
		jz	short loc_402058

loc_40203E:				; CODE XREF: sub_401F63+C3j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060A9,	1
		mov	ds:byte_406102,	0
		jmp	locret_40219D
; ---------------------------------------------------------------------------

loc_402058:				; CODE XREF: sub_401F63+CEj
					; sub_401F63+D9j
		movzx	eax, ds:byte_406102
		movsx	eax, al
		cmp	eax, 2
		jz	short loc_40207A
		cmp	eax, 3
		jz	short loc_4020AA
		cmp	eax, 1
		jz	loc_402186
		jmp	loc_40215B
; ---------------------------------------------------------------------------

loc_40207A:				; CODE XREF: sub_401F63+102j
		mov	eax, ds:dword_40607C
		lea	edx, [eax-2]
		mov	eax, ds:dword_406054
		cmp	edx, eax
		jge	short loc_4020A5
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060A8,	1
		mov	ds:byte_406102,	1
		jmp	loc_40218C
; ---------------------------------------------------------------------------

loc_4020A5:				; CODE XREF: sub_401F63+126j
		jmp	loc_40218C
; ---------------------------------------------------------------------------

loc_4020AA:				; CODE XREF: sub_401F63+107j
		mov	ds:byte_406000,	0
		mov	eax, ds:dword_40604C
		cmp	eax, 0Bh
		jnz	short loc_4020D8
		mov	eax, ds:dword_40609C
		cmp	eax, 0Bh
		jz	short loc_4020D8
		mov	ds:byte_4060A4,	0
		mov	ds:byte_406102,	2
		jmp	loc_40218C
; ---------------------------------------------------------------------------

loc_4020D8:				; CODE XREF: sub_401F63+156j
					; sub_401F63+160j
		movzx	eax, ds:byte_406102
		cmp	al, 3
		jnz	short loc_402159
		movzx	eax, ds:byte_4060AE
		cmp	al, 1
		jnz	short loc_402159
		mov	eax, ds:dword_40610C
		test	eax, eax
		jz	short loc_402159
		mov	edx, ds:dword_4060C0
		mov	eax, ds:dword_40610C
		sub	edx, eax
		mov	eax, edx
		mov	dword ptr [ebp+var_10],	eax
		mov	dword ptr [ebp+var_10+4], 0
		fild	[ebp+var_10]
		fstp	[ebp+var_8]
		fld	[ebp+var_8]
		fld	ds:dbl_403008
		fucomip	st, st(1)
		jp	short loc_402189
		fld	ds:dbl_403008
		fucomip	st, st(1)
		fstp	st
		jz	short loc_402131
		jmp	short loc_40218B
; ---------------------------------------------------------------------------

loc_402131:				; CODE XREF: sub_401F63+1CAj
		mov	eax, ds:dword_40604C
		add	eax, 1
		mov	ds:dword_40604C, eax
		mov	edx, ds:dword_406054
		mov	eax, ds:dword_40607C
		cmp	edx, eax
		jle	short loc_402159
		mov	eax, ds:dword_406054
		mov	ds:dword_40607C, eax
		jmp	short loc_40218B
; ---------------------------------------------------------------------------

loc_402159:				; CODE XREF: sub_401F63+17Ej
					; sub_401F63+189j ...
		jmp	short loc_40218B
; ---------------------------------------------------------------------------

loc_40215B:				; CODE XREF: sub_401F63+112j
		mov	ds:byte_4060A4,	0
		mov	ds:dword_40604C, 0
		mov	ds:dword_40607C, 2
		mov	ds:byte_406102,	3
		mov	ds:byte_406000,	1
		jmp	short loc_40218C
; ---------------------------------------------------------------------------

loc_402186:				; CODE XREF: sub_401F63+10Cj
		nop
		jmp	short locret_40219D
; ---------------------------------------------------------------------------

loc_402189:				; CODE XREF: sub_401F63+1BEj
		fstp	st

loc_40218B:				; CODE XREF: sub_401F63+1CCj
					; sub_401F63+1F4j ...
		nop

loc_40218C:				; CODE XREF: sub_401F63+13Dj
					; sub_401F63:loc_4020A5j ...
		jmp	short locret_40219D
; ---------------------------------------------------------------------------

loc_40218E:				; CODE XREF: sub_401F63+51j
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060A9,	1
		nop

locret_40219D:				; CODE XREF: sub_401F63+37j
					; sub_401F63+A5j ...
		leave
		retn
sub_401F63	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_40219F	proc near		; CODE XREF: sub_402912+Dp
		push	ebp
		mov	ebp, esp
		mov	ds:dword_4060C0, 1
		mov	ds:byte_4060A4,	0
		mov	ds:byte_4060AE,	0
		jmp	loc_402901
; ---------------------------------------------------------------------------

loc_4021BF:				; CODE XREF: sub_40219F+76Bj
		mov	ds:byte_4060A4,	1
		movzx	eax, ds:byte_4060AE
		add	eax, 1
		mov	ds:byte_4060AE,	al
		movzx	eax, ds:byte_4060FA
		movsx	eax, al
		cmp	eax, 2
		jz	short loc_40222E
		cmp	eax, 3
		jz	loc_402290
		cmp	eax, 1
		jnz	loc_4022C2
		movzx	eax, ds:byte_4060A7
		test	al, al
		jnz	short loc_402229
		movzx	eax, ds:byte_406110
		test	al, al
		jz	short loc_402229
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406090, 0
		mov	ds:byte_4060FA,	2
		jmp	loc_4022DB
; ---------------------------------------------------------------------------

loc_402229:				; CODE XREF: sub_40219F+60j
					; sub_40219F+6Bj
		jmp	loc_4022DB
; ---------------------------------------------------------------------------

loc_40222E:				; CODE XREF: sub_40219F+43j
		movzx	eax, ds:byte_4060A7
		test	al, al
		jz	short loc_40225E
		movzx	eax, ds:byte_406110
		test	al, al
		jnz	short loc_40225E
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406090, 0FFFFFF9Ch
		mov	ds:byte_4060FA,	1
		jmp	short loc_4022DB
; ---------------------------------------------------------------------------

loc_40225E:				; CODE XREF: sub_40219F+98j
					; sub_40219F+A3j
		movzx	eax, ds:byte_40605D
		test	al, al
		jz	short loc_40228E
		movzx	eax, ds:byte_4060C4
		test	al, al
		jnz	short loc_40228E
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406090, 64h
		mov	ds:byte_4060FA,	3
		jmp	short loc_4022DB
; ---------------------------------------------------------------------------

loc_40228E:				; CODE XREF: sub_40219F+C8j
					; sub_40219F+D3j
		jmp	short loc_4022DB
; ---------------------------------------------------------------------------

loc_402290:				; CODE XREF: sub_40219F+48j
		movzx	eax, ds:byte_40605D
		test	al, al
		jnz	short loc_4022C0
		movzx	eax, ds:byte_4060C4
		test	al, al
		jz	short loc_4022C0
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406090, 0
		mov	ds:byte_4060FA,	2
		jmp	short loc_4022DB
; ---------------------------------------------------------------------------

loc_4022C0:				; CODE XREF: sub_40219F+FAj
					; sub_40219F+105j
		jmp	short loc_4022DB
; ---------------------------------------------------------------------------

loc_4022C2:				; CODE XREF: sub_40219F+51j
		mov	ds:byte_4060A4,	0
		mov	ds:dword_406090, 0
		mov	ds:byte_4060FA,	2
		nop

loc_4022DB:				; CODE XREF: sub_40219F+85j
					; sub_40219F:loc_402229j ...
		movzx	eax, ds:byte_40600A
		test	al, al
		jnz	short loc_4022ED
		mov	ds:byte_4060F6,	3

loc_4022ED:				; CODE XREF: sub_40219F+145j
		mov	ds:byte_40600B,	0
		movzx	eax, ds:byte_406010
		test	al, al
		jnz	short loc_402306
		mov	ds:byte_406114,	1

loc_402306:				; CODE XREF: sub_40219F+15Ej
		mov	ds:byte_406011,	0
		movzx	eax, ds:byte_406013
		test	al, al
		jnz	short loc_402326
		mov	ds:byte_406000,	0
		mov	ds:byte_4060A9,	1

loc_402326:				; CODE XREF: sub_40219F+177j
		mov	ds:byte_406014,	0
		movzx	eax, ds:byte_40600D
		test	al, al
		jnz	short loc_40236C
		mov	ds:byte_406004,	0
		mov	ds:byte_406006,	0
		mov	ds:byte_4060D8,	2
		mov	ds:dword_406058, 0
		mov	ds:byte_4060EA,	1
		mov	ds:byte_406005,	1
		mov	ds:byte_406078,	1

loc_40236C:				; CODE XREF: sub_40219F+197j
		mov	ds:byte_40600E,	0
		mov	ds:byte_40600B,	1
		mov	ds:byte_406011,	1
		mov	ds:byte_406014,	1
		mov	ds:byte_40600E,	1
		movzx	edx, ds:byte_406112
		movzx	eax, ds:byte_4060C9
		cmp	dl, al
		jz	short loc_4023B8
		movzx	eax, ds:byte_40608C
		test	al, al
		jnz	short loc_4023B8
		movzx	eax, ds:byte_406112
		mov	ds:byte_406046,	al

loc_4023B8:				; CODE XREF: sub_40219F+200j
					; sub_40219F+20Bj
		movzx	edx, ds:byte_4060E0
		movzx	eax, ds:byte_4060B4
		cmp	dl, al
		jz	short loc_4023E1
		movzx	eax, ds:byte_40608C
		test	al, al
		jz	short loc_4023E1
		movzx	eax, ds:byte_4060E0
		mov	ds:byte_406112,	al

loc_4023E1:				; CODE XREF: sub_40219F+229j
					; sub_40219F+234j
		movzx	edx, ds:byte_4060EC
		movzx	eax, ds:byte_406048
		cmp	dl, al
		jz	short loc_40240A
		movzx	eax, ds:byte_40608C
		test	al, al
		jnz	short loc_40240A
		movzx	eax, ds:byte_4060EC
		mov	ds:byte_406115,	al

loc_40240A:				; CODE XREF: sub_40219F+252j
					; sub_40219F+25Dj
		movzx	edx, ds:byte_4060AD
		movzx	eax, ds:byte_406101
		cmp	dl, al
		jz	short loc_402433
		movzx	eax, ds:byte_40608C
		test	al, al
		jz	short loc_402433
		movzx	eax, ds:byte_4060AD
		mov	ds:byte_4060EC,	al

loc_402433:				; CODE XREF: sub_40219F+27Bj
					; sub_40219F+286j
		movzx	eax, ds:byte_40600C
		mov	ds:byte_40600A,	al
		movzx	eax, ds:byte_40600F
		mov	ds:byte_40600D,	al
		movzx	eax, ds:byte_406012
		mov	ds:byte_406010,	al
		movzx	eax, ds:byte_406015
		mov	ds:byte_406013,	al
		movzx	eax, ds:byte_4060D0
		mov	ds:byte_4060A5,	al
		movzx	eax, ds:byte_406115
		mov	ds:byte_406098,	al
		movzx	eax, ds:byte_406049
		mov	ds:byte_4060C5,	al
		movzx	eax, ds:byte_406046
		mov	ds:byte_406047,	al
		call	sub_401265
		movzx	eax, ds:byte_406108
		mov	ds:byte_40605D,	al
		movzx	eax, ds:byte_4060B5
		mov	ds:byte_4060A7,	al
		mov	eax, ds:dword_406054
		mov	ds:dword_406088, eax
		movzx	eax, ds:byte_4060AF
		mov	ds:byte_406082,	al
		mov	eax, ds:dword_4060F0
		mov	ds:dword_406068, eax
		movzx	eax, ds:byte_40605E
		mov	ds:byte_40609A,	al
		movzx	eax, ds:byte_4060A5
		mov	ds:byte_4060D0,	al
		movzx	eax, ds:byte_406098
		mov	ds:byte_406115,	al
		movzx	eax, ds:byte_4060C5
		mov	ds:byte_406049,	al
		movzx	eax, ds:byte_406047
		mov	ds:byte_406046,	al
		movzx	eax, ds:byte_4060F7
		mov	ds:byte_406080,	al
		movzx	eax, ds:byte_406094
		mov	ds:byte_406100,	al
		movzx	eax, ds:byte_4060D0
		mov	ds:byte_4060A5,	al
		movzx	eax, ds:byte_406115
		mov	ds:byte_406098,	al
		movzx	eax, ds:byte_406049
		mov	ds:byte_4060C5,	al
		movzx	eax, ds:byte_406046
		mov	ds:byte_406047,	al
		call	sub_401639
		movzx	eax, ds:byte_406108
		mov	ds:byte_40605D,	al
		movzx	eax, ds:byte_4060B5
		mov	ds:byte_4060A7,	al
		mov	eax, ds:dword_406054
		mov	ds:dword_406088, eax
		movzx	eax, ds:byte_4060AF
		mov	ds:byte_406082,	al
		mov	eax, ds:dword_4060F0
		mov	ds:dword_406068, eax
		movzx	eax, ds:byte_40605E
		mov	ds:byte_40609A,	al
		movzx	eax, ds:byte_4060A5
		mov	ds:byte_4060D0,	al
		movzx	eax, ds:byte_406098
		mov	ds:byte_406115,	al
		movzx	eax, ds:byte_4060C5
		mov	ds:byte_406049,	al
		movzx	eax, ds:byte_406047
		mov	ds:byte_406046,	al
		movzx	eax, ds:byte_4060F7
		mov	ds:byte_406080,	al
		movzx	eax, ds:byte_406094
		mov	ds:byte_406100,	al
		movzx	eax, ds:byte_4060D0
		mov	ds:byte_4060A5,	al
		movzx	eax, ds:byte_406115
		mov	ds:byte_406098,	al
		movzx	eax, ds:byte_406049
		mov	ds:byte_4060C5,	al
		movzx	eax, ds:byte_406046
		mov	ds:byte_406047,	al
		call	sub_401EB6
		movzx	eax, ds:byte_406108
		mov	ds:byte_40605D,	al
		movzx	eax, ds:byte_4060B5
		mov	ds:byte_4060A7,	al
		mov	eax, ds:dword_406054
		mov	ds:dword_406088, eax
		movzx	eax, ds:byte_4060AF
		mov	ds:byte_406082,	al
		mov	eax, ds:dword_4060F0
		mov	ds:dword_406068, eax
		movzx	eax, ds:byte_40605E
		mov	ds:byte_40609A,	al
		movzx	eax, ds:byte_4060A5
		mov	ds:byte_4060D0,	al
		movzx	eax, ds:byte_406098
		mov	ds:byte_406115,	al
		movzx	eax, ds:byte_4060C5
		mov	ds:byte_406049,	al
		movzx	eax, ds:byte_406047
		mov	ds:byte_406046,	al
		movzx	eax, ds:byte_4060F7
		mov	ds:byte_406080,	al
		movzx	eax, ds:byte_406094
		mov	ds:byte_406100,	al
		movzx	eax, ds:byte_4060D0
		mov	ds:byte_4060A5,	al
		movzx	eax, ds:byte_406115
		mov	ds:byte_406098,	al
		movzx	eax, ds:byte_406049
		mov	ds:byte_4060C5,	al
		movzx	eax, ds:byte_406046
		mov	ds:byte_406047,	al
		call	sub_401F63
		movzx	eax, ds:byte_406108
		mov	ds:byte_40605D,	al
		movzx	eax, ds:byte_4060B5
		mov	ds:byte_4060A7,	al
		mov	eax, ds:dword_406054
		mov	ds:dword_406088, eax
		movzx	eax, ds:byte_4060AF
		mov	ds:byte_406082,	al
		mov	eax, ds:dword_4060F0
		mov	ds:dword_406068, eax
		movzx	eax, ds:byte_40605E
		mov	ds:byte_40609A,	al
		movzx	eax, ds:byte_4060A5
		mov	ds:byte_4060D0,	al
		movzx	eax, ds:byte_406098
		mov	ds:byte_406115,	al
		movzx	eax, ds:byte_4060C5
		mov	ds:byte_406049,	al
		movzx	eax, ds:byte_406047
		mov	ds:byte_406046,	al
		movzx	eax, ds:byte_4060F7
		mov	ds:byte_406080,	al
		movzx	eax, ds:byte_406094
		mov	ds:byte_406100,	al
		movzx	eax, ds:byte_40600A
		mov	ds:byte_40600B,	al
		movzx	eax, ds:byte_40600D
		mov	ds:byte_40600E,	al
		movzx	eax, ds:byte_406010
		mov	ds:byte_406011,	al
		movzx	eax, ds:byte_406013
		mov	ds:byte_406014,	al
		mov	eax, ds:dword_406058
		mov	ds:dword_4060D4, eax
		mov	eax, ds:dword_406054
		mov	ds:dword_4060DC, eax
		mov	eax, ds:dword_4060BC
		mov	ds:dword_406090, eax
		mov	eax, ds:dword_406088
		mov	ds:dword_406074, eax
		mov	eax, ds:dword_40604C
		mov	ds:dword_40609C, eax
		movzx	eax, ds:byte_406047
		mov	ds:byte_406097,	al
		movzx	eax, ds:byte_4060C5
		mov	ds:byte_406099,	al
		movzx	eax, ds:byte_406098
		mov	ds:byte_4060C8,	al
		movzx	eax, ds:byte_4060A5
		mov	ds:byte_4060F5,	al
		movzx	eax, ds:byte_4060A8
		mov	ds:byte_406094,	al
		movzx	eax, ds:byte_406094
		mov	ds:byte_4060AB,	al
		movzx	eax, ds:byte_4060FB
		mov	ds:byte_4060F4,	al
		movzx	eax, ds:byte_4060F4
		mov	ds:byte_40606D,	al
		movzx	eax, ds:byte_4060C6
		mov	ds:byte_406083,	al
		movzx	eax, ds:byte_406083
		mov	ds:byte_406084,	al
		movzx	eax, ds:byte_4060ED
		mov	ds:byte_4060B5,	al
		movzx	eax, ds:byte_4060B5
		mov	ds:byte_40605C,	al
		movzx	eax, ds:byte_406116
		mov	ds:byte_406108,	al
		movzx	eax, ds:byte_406108
		mov	ds:byte_4060A6,	al
		movzx	eax, ds:byte_4060AF
		mov	ds:byte_4060E8,	al
		movzx	eax, ds:byte_406082
		mov	ds:byte_4060EE,	al
		movzx	eax, ds:byte_4060EC
		mov	ds:byte_406048,	al
		movzx	eax, ds:byte_406112
		mov	ds:byte_4060C9,	al
		movzx	eax, ds:byte_4060E0
		mov	ds:byte_4060B4,	al
		movzx	eax, ds:byte_4060AD
		mov	ds:byte_406101,	al
		movzx	eax, ds:byte_4060F9
		mov	ds:byte_406100,	al
		movzx	eax, ds:byte_406100
		mov	ds:byte_406051,	al
		movzx	eax, ds:byte_406113
		mov	ds:byte_4060A7,	al
		movzx	eax, ds:byte_4060A7
		mov	ds:byte_406110,	al
		movzx	eax, ds:byte_4060AA
		mov	ds:byte_40605D,	al
		movzx	eax, ds:byte_40605D
		mov	ds:byte_4060C4,	al

loc_402901:				; CODE XREF: sub_40219F+1Bj
		movzx	eax, ds:byte_4060A4
		test	al, al
		jz	loc_4021BF
		pop	ebp
		retn
sub_40219F	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_402912	proc near		; CODE XREF: start+6p
		push	ebp
		mov	ebp, esp
		call	sub_4011D2
		call	sub_40100D
		call	sub_40219F
		mov	eax, 0
		pop	ebp
		retn
sub_402912	endp

; ---------------------------------------------------------------------------
		align 4
		dd 0FFFFFFFFh, 0
		dd 0FFFFFFFFh, 32h dup(0)
		dd 180h	dup(?)
_text		ends

; Section 2. (virtual address 00003000)
; Virtual size			: 00000024 (	 36.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00001E00
; Flags	40400040: Data Readable
; Alignment	: 8 bytes
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
; Segment alignment 'qword' can not be represented in assembly
_rdata		segment	para public 'DATA' use32
		assume cs:_rdata
		;org 403000h
dbl_403000	dq 0.5			; DATA XREF: sub_40100D+66r
					; sub_40100D+B0r ...
dbl_403008	dq 0.002		; DATA XREF: sub_401F63+1B6r
					; sub_401F63+1C0r
aGccGnu4_9_2	db 'GCC: (GNU) 4.9.2',0
		align 1000h
_rdata		ends

; Section 3. (virtual address 00004000)
; Virtual size			: 00000035 (	 53.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00002000
; Flags	40300040: Data Readable
; Alignment	: 4 bytes
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_buildid	segment	dword public 'DATA' use32
		assume cs:_buildid
		;org 404000h
		dd 3 dup(0)
		dd 2, 19h, 401Ch, 201Ch, 53445352h, 19F2AFC9h, 96DE2196h
		dd 0AD217B1Ch, 0E963BBF9h, 1, 73h dup(0)
		align 1000h
_buildid	ends

; Section 4. (virtual address 00005000)
; Virtual size			: 00000138 (	312.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00002200
; Flags	40300040: Data Readable
; Alignment	: 4 bytes
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_eh_fram	segment	dword public 'DATA' use32
		assume cs:_eh_fram
		;org 405000h
		dd 14h,	0
		dd 527A01h, 1087C01h, 4040C1Bh,	188h, 2	dup(1Ch), 0FFFFBFE0h
		dd 0Dh,	80E4100h, 0D420285h, 0CC54905h,	404h, 1Ch, 3Ch
		dd 0FFFFBFCDh, 1C5h, 80E4100h, 0D420285h, 1C10305h, 4040CC5h
		dd 1Ch,	5Ch, 0FFFFC172h, 93h, 80E4100h,	0D420285h, 0C58F0205h
		dd 4040Ch, 1Ch,	7Ch, 0FFFFC1E5h, 3D4h, 80E4100h, 0D420285h
		dd 3D00305h, 4040CC5h, 1Ch, 9Ch, 0FFFFC599h, 87Dh, 80E4100h
		dd 0D420285h, 8790305h,	4040CC5h, 1Ch, 0BCh, 0FFFFCDF6h
		dd 0ADh, 80E4100h, 0D420285h, 0C5A90205h, 4040Ch, 1Ch
		dd 0DCh, 0FFFFCE83h, 23Ch, 80E4100h, 0D420285h,	2380305h
		dd 4040CC5h, 1Ch, 0FCh,	0FFFFD09Fh, 773h, 80E4100h, 0D420285h
		dd 76F0305h, 4040CC5h, 1Ch, 11Ch, 0FFFFD7F2h, 19h, 80E4100h
		dd 0D420285h, 0CC55505h, 404h, 32h dup(0)
		align 1000h
_eh_fram	ends

; Section 5. (virtual address 00006000)
; Virtual size			: 00000117 (	279.)
; Section size in file		: 00000000 (	  0.)
; Offset to raw	data for section: 00000000
; Flags	C0700080: Bss Readable Writable
; Alignment	: 64 bytes
; ===========================================================================

; Segment type:	Uninitialized
; Segment permissions: Read/Write
; Segment alignment '64byte' can not be represented in assembly
_bss		segment	para public 'BSS' use32
		assume cs:_bss
		;org 406000h
		assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing
byte_406000	db ?			; DATA XREF: sub_40100D:loc_4011ACr
					; sub_401639+65w ...
		align 4
byte_406004	db ?			; DATA XREF: sub_40100D+6r
					; sub_40100D:loc_401028r ...
byte_406005	db ?			; DATA XREF: sub_401639+73Cw
					; sub_401639+79Cw ...
byte_406006	db ?			; DATA XREF: sub_40100D+26r
					; sub_401639+2Bw ...
byte_406007	db ?			; DATA XREF: sub_401639+876w
		db 2 dup(?)
byte_40600A	db ?			; DATA XREF: sub_401265+3r
					; sub_401639+41r ...
byte_40600B	db ?			; DATA XREF: sub_401639:loc_40168Cw
					; sub_401639+7Aw ...
byte_40600C	db ?			; DATA XREF: sub_40219F:loc_402433r
byte_40600D	db ?			; DATA XREF: sub_401639+3r
					; sub_401639:loc_40166Br ...
byte_40600E	db ?			; DATA XREF: sub_401639+19r
					; sub_40219F:loc_40236Cw ...
byte_40600F	db ?			; DATA XREF: sub_401639+Er
					; sub_40219F+2A0r
byte_406010	db ?			; DATA XREF: sub_401EB6+3r
					; sub_40219F+155r ...
byte_406011	db ?			; DATA XREF: sub_401639+4BEw
					; sub_401639+4F0w ...
byte_406012	db ?			; DATA XREF: sub_40219F+2ACr
byte_406013	db ?			; DATA XREF: sub_401639+5Ar
					; sub_401F63+6r ...
byte_406014	db ?			; DATA XREF: sub_401639:loc_4016ACw
					; sub_401639+81w ...
byte_406015	db ?			; DATA XREF: sub_401F63+11r
					; sub_40219F+2B8r
byte_406016	db ?			; DATA XREF: sub_401639+490r
					; sub_401639+57Er
byte_406017	db ?			; DATA XREF: sub_401639:loc_401AC2w
					; sub_401639+4E2w ...
byte_406018	db ?			; DATA XREF: sub_401639:loc_401B02r
					; sub_401639:loc_401BF6r ...
		align 40h
dword_406040	dd ?			; DATA XREF: sub_40100D:loc_401126r
					; sub_40100D+128r ...
byte_406044	db ?			; DATA XREF: sub_4011D2+59w
					; sub_401639:loc_401AA9r ...
byte_406045	db ?			; DATA XREF: sub_4011D2+52w
					; sub_401639+CBw ...
byte_406046	db ?			; DATA XREF: sub_40219F+214w
					; sub_40219F+2E8r ...
byte_406047	db ?			; DATA XREF: sub_401265+42r
					; sub_401265:loc_40131Dr ...
byte_406048	db ?			; DATA XREF: sub_40219F+249r
					; sub_40219F+6F1w
byte_406049	db ?			; DATA XREF: sub_40219F+2DCr
					; sub_40219F+35Cw ...
		align 4
dword_40604C	dd ?			; DATA XREF: sub_40100D+1AAr
					; sub_401F63+83w ...
byte_406050	db ?			; DATA XREF: sub_401639+1FBr
byte_406051	db ?			; DATA XREF: sub_40219F+72Dw
		align 4
dword_406054	dd ?			; DATA XREF: sub_401F63:loc_401FB9r
					; sub_401F63+65r ...
dword_406058	dd ?			; DATA XREF: sub_401639+A9r
					; sub_401639:loc_401820r ...
byte_40605C	db ?			; DATA XREF: sub_401F63+D0r
					; sub_40219F+6B5w
byte_40605D	db ?			; DATA XREF: sub_40219F:loc_40225Er
					; sub_40219F:loc_402290r ...
byte_40605E	db ?			; DATA XREF: sub_40219F+331r
					; sub_40219F+3F2r ...
		align 10h
dword_406060	dd ?			; DATA XREF: sub_40100D:loc_401092r
					; sub_40100D+94r ...
		align 8
dword_406068	dd ?			; DATA XREF: sub_40219F+32Cw
					; sub_40219F+3EDw ...
byte_40606C	db ?			; DATA XREF: sub_401639+4A9w
					; sub_401639+4DBw
byte_40606D	db ?			; DATA XREF: sub_401639+339r
					; sub_401639+385r ...
byte_40606E	db ?			; DATA XREF: sub_401639+206r
		align 10h
dword_406070	dd ?			; DATA XREF: sub_40100D+16w
					; sub_4011D2+17w ...
dword_406074	dd ?			; DATA XREF: sub_40219F+61Bw
byte_406078	db ?			; DATA XREF: sub_4011D2+4Bw
					; sub_401639+7A3w ...
		align 4
dword_40607C	dd ?			; DATA XREF: sub_401F63+8Dw
					; sub_401F63:loc_40207Ar ...
byte_406080	db ?			; DATA XREF: sub_40219F+374w
					; sub_40219F+435w ...
byte_406081	db ?			; DATA XREF: sub_4011D2+67w
					; sub_401639:loc_40194Er ...
byte_406082	db ?			; DATA XREF: sub_40219F+322w
					; sub_40219F+3E3w ...
byte_406083	db ?			; DATA XREF: sub_401639:loc_4017A2r
					; sub_401639:loc_4017C6r ...
byte_406084	db ?			; DATA XREF: sub_401639+34Fr
					; sub_401639+3ABr ...
		align 4
dword_406088	dd ?			; DATA XREF: sub_40219F+316w
					; sub_40219F+3D7w ...
byte_40608C	db ?			; DATA XREF: sub_40219F+202r
					; sub_40219F+22Br ...
		align 10h
dword_406090	dd ?			; DATA XREF: sub_40219F+74w
					; sub_40219F+ACw ...
byte_406094	db ?			; DATA XREF: sub_401639:loc_401715r
					; sub_401639:loc_40186Br ...
byte_406095	db ?			; DATA XREF: sub_401639+590w
					; sub_401639+5D6w
byte_406096	db ?			; DATA XREF: sub_4011D2+2Fw
					; sub_401265+180w ...
byte_406097	db ?			; DATA XREF: sub_401265+C3r
					; sub_401265+11Dr ...
byte_406098	db ?			; DATA XREF: sub_401265+37r
					; sub_401265+88r ...
byte_406099	db ?			; DATA XREF: sub_401265+1DAr
					; sub_401265+234r ...
byte_40609A	db ?			; DATA XREF: sub_40219F+338w
					; sub_40219F+3F9w ...
		align 4
dword_40609C	dd ?			; DATA XREF: sub_40100D+1B0r
					; sub_401F63+158r ...
dword_4060A0	dd ?			; DATA XREF: sub_40100D:loc_401169r
					; sub_40100D+16Br ...
byte_4060A4	db ?			; DATA XREF: sub_401265+4Dw
					; sub_401265+9Ew ...
byte_4060A5	db ?			; DATA XREF: sub_401265:loc_4013B3r
					; sub_401265+19Fr ...
byte_4060A6	db ?			; DATA XREF: sub_401F63+BAr
					; sub_40219F+6CDw
byte_4060A7	db ?			; DATA XREF: sub_40219F+57r
					; sub_40219F:loc_40222Er ...
byte_4060A8	db ?			; DATA XREF: sub_401F63+75w
					; sub_401F63+12Fw ...
byte_4060A9	db ?			; DATA XREF: sub_4011D2+8Aw
					; sub_401639+6Cw ...
byte_4060AA	db ?			; DATA XREF: sub_40219F+74Ar
byte_4060AB	db ?			; DATA XREF: sub_401639+E7r
					; sub_401639+23Dr ...
		db ?
byte_4060AD	db ?			; DATA XREF: sub_40219F:loc_40240Ar
					; sub_40219F+288r ...
byte_4060AE	db ?			; DATA XREF: sub_401639+743r
					; sub_401639+7BEr ...
byte_4060AF	db ?			; DATA XREF: sub_401EB6:loc_401EDEr
					; sub_401EB6+74r ...
dword_4060B0	dd ?			; DATA XREF: sub_40100D:loc_4010DCr
					; sub_40100D+DEr ...
byte_4060B4	db ?			; DATA XREF: sub_40219F+220r
					; sub_40219F+709w
byte_4060B5	db ?			; DATA XREF: sub_401639+F2r
					; sub_401639+294r ...
		align 4
dword_4060B8	dd ?			; DATA XREF: sub_40100D:loc_401048r
					; sub_40100D+4Ar ...
dword_4060BC	dd ?			; DATA XREF: sub_40219F+60Cr
dword_4060C0	dd ?			; DATA XREF: sub_40100D+11r
					; sub_40100D:loc_40103Er ...
byte_4060C4	db ?			; DATA XREF: sub_40219F+CAr
					; sub_40219F+FCr ...
byte_4060C5	db ?			; DATA XREF: sub_401265+159r
					; sub_401265:loc_401434r ...
byte_4060C6	db ?			; DATA XREF: sub_401265+5Bw
					; sub_401265+A5w ...
byte_4060C7	db ?			; DATA XREF: sub_4011D2+60w
					; sub_401639:loc_401B97r ...
byte_4060C8	db ?			; DATA XREF: sub_401265+93r
					; sub_401265+F0r ...
byte_4060C9	db ?			; DATA XREF: sub_40219F+1F7r
					; sub_40219F+6FDw
		align 10h
byte_4060D0	db ?			; DATA XREF: sub_40219F+2C4r
					; sub_40219F+344w ...
		align 4
dword_4060D4	dd ?			; DATA XREF: sub_401639+B3r
					; sub_401639+1F1r ...
byte_4060D8	db ?			; DATA XREF: sub_4011D2+3Dw
					; sub_401639+88r ...
		align 4
dword_4060DC	dd ?			; DATA XREF: sub_401F63+5Cr
					; sub_40219F+607w
byte_4060E0	db ?			; DATA XREF: sub_40219F:loc_4023B8r
					; sub_40219F+236r ...
		align 8
byte_4060E8	db ?			; DATA XREF: sub_401EB6+33r
					; sub_401EB6+7Fr ...
byte_4060E9	db ?			; DATA XREF: sub_4011D2+28w
					; sub_401265+69w ...
byte_4060EA	db ?			; DATA XREF: sub_4011D2+44w
					; sub_401639:loc_401D62r ...
		align 4
byte_4060EC	db ?			; DATA XREF: sub_40219F:loc_4023E1r
					; sub_40219F+25Fr ...
byte_4060ED	db ?			; DATA XREF: sub_40100D+BEw
					; sub_40100D+108w ...
byte_4060EE	db ?			; DATA XREF: sub_40219F+6E5w
		align 10h
dword_4060F0	dd ?			; DATA XREF: sub_401639+2EFr
					; sub_401639:loc_401A23r ...
byte_4060F4	db ?			; DATA XREF: sub_401639+145r
					; sub_401639:loc_4017E8r ...
byte_4060F5	db ?			; DATA XREF: sub_401265+1AAr
					; sub_401265+207r ...
byte_4060F6	db ?			; DATA XREF: sub_4011D2+36w
					; sub_401265+12r ...
byte_4060F7	db ?			; DATA XREF: sub_401265:loc_4014CAr
					; sub_401265:loc_40150Cr ...
byte_4060F8	db ?			; DATA XREF: sub_4011D2+21w
					; sub_401639:loc_401761r ...
byte_4060F9	db ?			; DATA XREF: sub_40219F+71Ar
byte_4060FA	db ?			; DATA XREF: sub_4011D2+75w
					; sub_40219F+36r ...
byte_4060FB	db ?			; DATA XREF: sub_401265+54w
					; sub_401265+D5w ...
dword_4060FC	dd ?			; DATA XREF: sub_40100D+36w
					; sub_4011D2+Dw ...
byte_406100	db ?			; DATA XREF: sub_40219F+380w
					; sub_40219F+441w ...
byte_406101	db ?			; DATA XREF: sub_40219F+272r
					; sub_40219F+715w
byte_406102	db ?			; DATA XREF: sub_4011D2+83w
					; sub_401F63+97w ...
		align 8
byte_406108	db ?			; DATA XREF: sub_401639+248r
					; sub_401639+776r ...
		align 4
dword_40610C	dd ?			; DATA XREF: sub_40100D+1BEw
					; sub_4011D2+3w ...
byte_406110	db ?			; DATA XREF: sub_40219F+62r
					; sub_40219F+9Ar ...
byte_406111	db ?			; DATA XREF: sub_4011D2+6Ew
					; sub_401639:loc_401A46r ...
byte_406112	db ?			; DATA XREF: sub_40219F+1F0r
					; sub_40219F+20Dr ...
byte_406113	db ?			; DATA XREF: sub_40219F+732r
byte_406114	db ?			; DATA XREF: sub_4011D2+7Cw
					; sub_401EB6+12r ...
byte_406115	db ?			; DATA XREF: sub_40219F+266w
					; sub_40219F+2D0r ...
byte_406116	db ?			; DATA XREF: sub_40100D+74w
					; sub_401639+17Bw ...
		align 1000h
_bss		ends

; Section 6. (virtual address 00007000)
; Virtual size			: 00000014 (	 20.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00002400
; Flags	C0300040: Data Readable	Writable
; Alignment	: 4 bytes
; ===========================================================================

; Segment type:	Externs
; _idata




		end start
